
	#define OFF /* C_0 - OFF */ 0
	#define ON /* C_1 - ON */ 1
	
	
	enum EN0 {
		CA2GUI_PRESENCE_SENSOR_ERROR /* CA2GUI_PRESENCE_SENSOR_ERROR */,
		CA2GUI_COLOR_SENSORS_ERROR /* CA2GUI_COLOR_SENSORS_ERROR */
	
	};