
	#define ON /* C_0 - ON */ 1
	#define OFF /* C_1 - OFF */ 0
	#define AlgorithmDelay /* C_2 - AlgorithmDelay */ 40 
	#define TestIdling /* C_3 - TestIdling */ 100

	
	enum EN0 {
		D2V_TEST_NORMAL_TURN_ON /* D2V_TEST_NORMAL_TURN_ON */, 
		D2V_TEST_NORMAL_TURN_OFF /* D2V_TEST_NORMAL_TURN_OFF */, 
		D2V_FINISH_VERIFICATION /* D2V_FINISH_VERIFICATION */
	
	};

	
	enum EN1 {
		V2D_START_VERIFICATION /* V2D_START_VERIFICATION */
	
	};

	
	enum EN2 {
		V2GUI_TEST_PASSED_NORMAL_TURN_ON /* V2GUI_TEST_PASSED_NORMAL_TURN_ON */, 
		V2GUI_TEST_FAILED_NORMAL_TURN_ON /* V2GUI_TEST_FAILED_NORMAL_TURN_ON */,
		V2GUI_START_TEST_TURN_ON /* V2GUI_START_TEST_TURN_ON */,
		V2GUI_TEST_PASSED_NORMAL_TURN_OFF /* V2GUI_TEST_PASSED_NORMAL_TURN_OFF */, 
		V2GUI_TEST_FAILED_NORMAL_TURN_OFF /* V2GUI_TEST_FAILED_NORMAL_TURN_OFF */,
		V2GUI_START_TEST_TURN_OFF /* V2GUI_START_TEST_TURN_OFF */,
		V2GUI_END_VERIFICATION /* V2GUI_END_VERIFICATION */
	
	};