
	#define ON /* C_0 - ON */ 1
	#define OFF /* C_1 - OFF */ 0
	#define AlgorithmDelay /* C_2 - AlgorithmDelay */ 40 
	#define TestIdling /* C_3 - TestIdling */ 100

	
	enum EN0 {
		SCM2VM_TEST_NORMAL_TURN_ON /* SCM2VM_TEST_NORMAL_TURN_ON */,
		SCM2VM_TEST_NORMAL_TURN_OFF /* SCM2VM_TEST_NORMAL_TURN_OFF */, 
		SCM2VM_FINISH_VERIFICATION /* SCM2VM_FINISH_VERIFICATION */
	
	};

	
	enum EN1 {
		VM2SCM_START_VERIFICATION /* VM2SCM_START_VERIFICATION */,
		VM2SCM_NEXT_TEST /* VM2SCM_NEXT_TEST */
	
	};

	
	enum EN2 {
		VM2GUI_TEST_PASSED_NORMAL_TURN_ON /* VM2GUI_TEST_PASSED_NORMAL_TURN_ON */, 
		VM2GUI_TEST_PASSED_NORMAL_TURN_OFF /* VM2GUI_TEST_PASSED_NORMAL_TURN_OFF */,
		VM2GUI_TEST_FAILED_NORMAL_TURN_ON /* VM2GUI_TEST_FAILED_NORMAL_TURN_ON */,
		VM2GUI_TEST_FAILED_NORMAL_TURN_OFF /* VM2GUI_TEST_FAILED_NORMAL_TURN_OFF */,
		VM2GUI_TEST_NOT_ACTIVE_NORMAL_TURN_ON /* VM2GUI_TEST_NOT_ACTIVE_NORMAL_TURN_ON */,
		VM2GUI_TEST_NOT_ACTIVE_NORMAL_TURN_OFF /* VM2GUI_TEST_NOT_ACTIVE_NORMAL_TURN_OFF */,
		VM2GUI_START_TEST_TURN_ON /* VM2GUI_START_TEST_TURN_ON */,
		VM2GUI_START_TEST_TURN_OFF /* VM2GUI_START_TEST_TURN_OFF */,
		VM2GUI_END_VERIFICATION /* VM2GUI_END_VERIFICATION */
	
	};