
	#define ON /* C_0 - ON */ 1
	#define OFF /* C_1 - OFF */ 0
	#define PCyclesDelay /* C_2 - PCyclesDelay */ 200 
	#define KCyclesDelay /* C_3 - KCyclesDelay */ 150 
	#define AlgorithmDelay /* C_4 - AlgorithmDelay */ 10 
	#define TestIdling /* C_5 - TestIdling */ 400 

	
	enum EN0 {
		SCM2VM_TEST_TRAFFIC_LIGHT_CYCLE /* SCM2VM_TEST_TRAFFIC_LIGHT_CYCLE */, 
		SCM2VM_FINISH_VERIFICATION /* SCM2VM_FINISH_VERIFICATION */
	
	};

	
	enum EN1 {
		VM2SCM_START_VERIFICATION /* VM2SCM_START_VERIFICATION */,
		VM2SCM_NEXT_TEST /* VM2SCM_NEXT_TEST */
	
	};

	
	enum EN2 {
		VM2GUI_TEST_PASSED_PAUSE_P_CYCLES /* VM2GUI_TEST_PASSED_PAUSE_P_CYCLES */, 
		VM2GUI_TEST_PASSED_DISABLE_MOTION_FOR_K_CYCLES /* VM2GUI_TEST_PASSED_DISABLE_MOTION_FOR_K_CYCLES */,
		VM2GUI_TEST_FAILED_PAUSE_P_CYCLES /* VM2GUI_TEST_FAILED_PAUSE_P_CYCLES */,
		VM2GUI_TEST_FAILED_DISABLE_MOTION_FOR_K_CYCLES /* VM2GUI_TEST_FAILED_DISABLE_MOTION_FOR_K_CYCLES */,
		VM2GUI_START_TEST_PAUSE_P_CYCLES /* VM2GUI_START_TEST_PAUSE_P_CYCLES */,
		VM2GUI_START_TEST_DISABLE_MOTION_FOR_K_CYCLES /* VM2GUI_START_TEST_DISABLE_MOTION_FOR_K_CYCLES */,
		VM2GUI_END_VERIFICATION /* VM2GUI_END_VERIFICATION */
	
	};