
	#define PCyclesDelay /* C_0 - PCyclesDelay */ 198 
	#define KCyclesDelay /* C_1 - KCyclesDelay */ 148 
	#define AlgorithmDelay /* C_2 - AlgorithmDelay */ 10 
	#define Active /* C_3 - Active */ 1
	#define Error /* C_4 - Error */ 0

	
	enum EN0 {
		SCM2VM_TEST_RUN_CARS /* SCM2VM_TEST_RUN_CARS */,
		SCM2VM_TEST_NO_CARS /* SCM2VM_TEST_NO_CARS */,
		SCM2VM_TEST_RUN_WRONG_CAR /* SCM2VM_TEST_RUN_WRONG_CAR */, 
		SCM2VM_TEST_COMPLETED /* SCM2VM_TEST_COMPLETED */,
		SCM2VM_FINISH_VERIFICATION /* SCM2VM_FINISH_VERIFICATION */
	
	};

	 
	enum EN1 {
		VM2SCM_START_VERIFICATION /* VM2SCM_START_VERIFICATION */
	
	};

	
	enum EN2 {
		VM2GUI_START_TEST_RUN_CARS /* VM2GUI_START_TEST_RUN_CARS */,
		VM2GUI_START_TEST_NO_CARS /* VM2GUI_START_TEST_NO_CARS */,
		VM2GUI_START_TEST_RUN_WRONG_CAR /* VM2GUI_START_TEST_RUN_WRONG_CAR */,
		VM2GUI_TEST_PASSED_NO_CARS /* VM2GUI_TEST_PASSED_NO_CARS */,
		VM2GUI_TEST_PASSED_NORMAL_OPEN_ROAD_DELAY /* VM2GUI_TEST_PASSED_NORMAL_OPEN_ROAD_DELAY */, 
		VM2GUI_TEST_PASSED_NORMAL_CLOSE_ROAD_DELAY /* VM2GUI_TEST_PASSED_NORMAL_CLOSE_ROAD_DELAY */,
		VM2GUI_TEST_FAILED_NO_CARS /* VM2GUI_TEST_FAILED_NO_CARS */,
		VM2GUI_TEST_FAILED_NORMAL_OPEN_ROAD_DELAY /* VM2GUI_TEST_FAILED_NORMAL_OPEN_ROAD_DELAY */,
		VM2GUI_TEST_FAILED_NORMAL_CLOSE_ROAD_DELAY /* VM2GUI_TEST_FAILED_NORMAL_CLOSE_ROAD_DELAY */,
		VM2GUI_END_VERIFICATION /* VM2GUI_END_VERIFICATION */
	
	};