
#define ON /* C_0 - ON */ 1
#define OFF /* C_1 - OFF */ 0

#define Idiling /* C_2 - Idiling */ 0
#define RunNextTest /* C_3 - RunNextTest */ 1

 
enum EN0 {
	SCM2VP_INSERT_HANDS /* SCM2VP_INSERT_HANDS */,
	SCM2VP_TAKE_AWAY_HANDS /* SCM2VP_TAKE_AWAY_HANDS */

};
 
enum EN1 {
	SCM2VM_TEST_DRYER_NORMAL_TURN_ON /* SCM2VM_TEST_DRYER_NORMAL_TURN_ON */,
	SCM2VM_TEST_DRYER_NORMAL_TURN_OFF /* SCM2VM_TEST_DRYER_NORMAL_TURN_OFF */, 
	SCM2VM_FINISH_VERIFICATION /* SCM2VM_FINISH_VERIFICATION */

};

enum EN2 {
	VM2SCM_START_VERIFICATION /* VM2SCM_START_VERIFICATION */,
	VM2SCM_NEXT_TEST /* VM2SCM_NEXT_TEST */

};