
#define ON /* C_0 - ON */ 1
#define OFF /* C_1 - OFF */ 0
#define SENSOR_DELAY /* C_2 - SENSOR_DELAY */ 3

enum EN0 {
	SCM2VP_INSERT_HANDS /* SCM2VP_INSERT_HANDS */,
	SCM2VP_TAKE_AWAY_HANDS /* SCM2VP_TAKE_AWAY_HANDS */

};