

#define H /* C_0 - H */		0.6
#define U_MIN /* C_1 - U_MIN */	0.0	
#define U_MAX /* C_2 - U_MAX */	15.0
#define DELTA_U /* C_3 - DELTA_U */ 10.0
#define DELTA_X /* C_4 - DELTA_X */ 0.1

#define IDILING_DELAY /* C_5 - IDILING_DELAY */ 100
#define CONTROLLER_DELAY /* C_6 - CONTROLLER_DELAY */ 200

enum EN0 {
	VM2SCM_START_VERIFICATION /* VM2SCM_START_VERIFICATION */,
	VM2SCM_NEXT_TEST /* VM2SCM_NEXT_TEST */

};

enum EN1 {
		CA2GUI_X_LEVEL /* CA2GUI_X_LEVEL */,
		CA2GUI_U_LEVEL /* CA2GUI_U_LEVEL */

};


enum EN2 {
	SCM2VM_StartTestNewDesiredLevel /* SCM2VM_StartTestNewDesiredLevel */,
	SCM2VM_FINISH_VERIFICATION /* SCM2VM_FINISH_VERIFICATION */

};

enum EN3 {
	VM2GUI_TEST_FAILED_U_MAX /* VM2GUI_TEST_FAILED_U_MAX */,
	VM2GUI_TEST_FAILED_U_MIN /* VM2GUI_TEST_FAILED_U_MIN */, 
	VM2GUI_TEST_FAILED_OWERFLOW /* VM2GUI_TEST_FAILED_OWERFLOW */,
	VM2GUI_TEST_FAILED_UNDERFILL /* VM2GUI_TEST_FAILED_UNDERFILL */,	
	VM2GUI_TEST_FAILED_DELTA_U /* VM2GUI_TEST_FAILED_DELTA_U */,
	VM2GUI_TEST_FAILED_BIG_LEVEL_DIFFERENCE /* VM2GUI_TEST_FAILED_BIG_LEVEL_DIFFERENCE */,
	VM2GUI_TEST_PASSED_X_LEVEL_CONTROL /* VM2GUI_TEST_PASSED_X_LEVEL_CONTROL */,	
	VM2GUI_X_LEVEL /* VM2GUI_X_LEVEL */,
	VM2GUI_END_VERIFICATION /* VM2GUI_END_VERIFICATION */

};