
	#define TestIdling1 /* C_0 - TestIdling1 */ 600 
	#define TestIdling2 /* C_1 - TestIdling2 */ 300 
	#define TestIdling3 /* C_2 - TestIdling3 */ 300 
 
	
	enum EN0 {		
		SCM2VP_PUT_BOXES_ON_CONVEYOR /* SCM2VP_PUT_BOXES_ON_CONVEYOR */,
		SCM2VP_BROKEN_PRESENCE_SENSOR /* SCM2VP_BROKEN_PRESENCE_SENSOR */,
		SCM2VP_BROKEN_COLOR_SENSORS /* SCM2VP_BROKEN_COLOR_SENSORS */,
		SCM2VP_FINISH_VERIFICATION /* SCM2VP_FINISH_VERIFICATION */
	
	};
 
		
	enum EN1 {
		SCM2VM_TEST_PUT_BOXES_ON_CONVEYOR /* SCM2VM_TEST_PUT_BOXES_ON_CONVEYOR */,
		SCM2VM_TEST_BROKEN_PRESENCE_SENSOR /* SCM2VM_TEST_BROKEN_PRESENCE_SENSOR */,
		SCM2VM_TEST_BROKEN_COLOR_SENSORS /* SCM2VM_TEST_BROKEN_COLOR_SENSORS */,
		SCM2VM_TEST_COMPLETED /* SCM2VM_TEST_COMPLETED */,
		SCM2VM_FINISH_VERIFICATION /* SCM2VM_FINISH_VERIFICATION */
	
	};

	
	enum EN2 {
		VM2SCM_START_VERIFICATION /* VM2SCM_START_VERIFICATION */
	
	};