
	
	#define Idiling /* C_0 - Idiling */ 0
	#define RunNextTest /* C_1 - RunNextTest */ 1
 
	
	enum EN0 {		
		SCM2VP_PUT_BOXES_ON_CONVEYOR /* SCM2VP_PUT_BOXES_ON_CONVEYOR */,
		SCM2VP_BROKEN_PRESENCE_SENSOR /* SCM2VP_BROKEN_PRESENCE_SENSOR */,
		SCM2VP_BROKEN_COLOR_SENSORS /* SCM2VP_BROKEN_COLOR_SENSORS */,
		SCM2VP_FINISH_VERIFICATION /* SCM2VP_FINISH_VERIFICATION */
	
	};
 
		
	enum EN1 {
		SCM2VM_TEST_PUT_BOXES_ON_CONVEYOR /* SCM2VM_TEST_PUT_BOXES_ON_CONVEYOR */,
		SCM2VM_TEST_BROKEN_PRESENCE_SENSOR /* SCM2VM_TEST_BROKEN_PRESENCE_SENSOR */,
		SCM2VM_TEST_BROKEN_COLOR_SENSORS /* SCM2VM_TEST_BROKEN_COLOR_SENSORS */,
		SCM2VM_FINISH_VERIFICATION /* SCM2VM_FINISH_VERIFICATION */
	
	};

	
	enum EN2 {
		VM2SCM_START_VERIFICATION /* VM2SCM_START_VERIFICATION */,
		VM2SCM_NEXT_TEST /* VM2SCM_NEXT_TEST */
	
	};